# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9e22cccade9ddf563dc7a038ddacb4f2"
name = "experiments"
application_url = "https://bedding-moment-middle-billion.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-7e3161e7.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bedding-moment-middle-billion.trycloudflare.com/auth/callback",
  "https://bedding-moment-middle-billion.trycloudflare.com/auth/shopify/callback",
  "https://bedding-moment-middle-billion.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
