# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3778507ce8907b75408992a96b3e6137"
name = "experiments-dev"
handle = "experiments-dev"
application_url = "https://words-paintings-below-china.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-7e3161e7.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://words-paintings-below-china.trycloudflare.com/auth/callback",
  "https://words-paintings-below-china.trycloudflare.com/auth/shopify/callback",
  "https://words-paintings-below-china.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
